// cmd/setup/templates/app/src/components/Header/Header.component.tsx
import * as React from 'react';
import { hot } from 'react-hot-loader/root';
import { connect } from 'react-redux';
import { Button, ButtonPriority } from '@pyramidlabs/react-ui';
import { UrlConfig } from '../../config';
import './header.scss';
import { ApplicationState } from '@app/redux/Reducers/Reducer';
import { bindActionCreators, Dispatch } from "redux";
import { Actions } from "@app/redux/Actions/Authentication";

export const mapStateToProps = (
  state: ApplicationState
): HeaderComponentState => ({
  userName: (state.authentication && state.authentication.user) ? state.authentication.user.name : null,
  isAuthenticated: Boolean(state.authentication && state.authentication.user)
});

export const mapDispatchToProps = (dispatch: Dispatch) =>
     ({ logout: () => dispatch(Actions.logout()) });

type HeaderComponentState = { userName?: string; isAuthenticated?: boolean };
type ReduxStateToProps = ReturnType<typeof mapStateToProps>;
type ReduxDispatchToProps = ReturnType<typeof mapDispatchToProps>;
type HeaderProps = HeaderComponentState &
  ReduxDispatchToProps &
  ReduxStateToProps;

export class HeaderComponent extends React.Component<HeaderProps> {
  render = () => {
    return (
      <header className="header-component">
        <div className="section left">
          <div className="image" />
          <h1 className="application-title">Application Title</h1>
        </div>
        <div className="section right">{this.renderLogin()}</div>
      </header>
    );
  };

  renderLogin = () => {
    if (this.props.isAuthenticated) {
      return (
        <div className="logged-in-user-section">
          <div className="user-menu-button">
            <span className="fas fa-user user-icon" />
            <span className="username">{this.props.userName}</span>
            <span className="fas fa-caret-down" />
          </div>
          <Button text={'Logout'} priority={ButtonPriority.Primary} onClick={this.props.logout} />
        </div>
      );
    } else {
      const loginUrl = `${UrlConfig.apiUrl}auth/login`;
      return (
        <a href={loginUrl}>
          <Button text={'Login'} priority={ButtonPriority.Primary} />
        </a>
      );
    }
  };
}

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(hot(HeaderComponent));

// cmd/setup/templates/app/src/app/components/header/header.component.ts
import { Component, OnInit } from '@angular/core';
import { faUser, faCaretDown } from '@fortawesome/free-solid-svg-icons';
import { UrlService } from '../../service/url/url.service';
import { AuthService } from '../../service/auth/auth.service';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss']
})
export class HeaderComponent implements OnInit {
  username: string;
  expiry: number;
  faUser = faUser;
  faCaretDown = faCaretDown;
  constructor(private urlService: UrlService, private authService: AuthService) {
    this.authService.currentUser.subscribe(res => {
      this.username = res && res.name;
      this.expiry = res && (res.exp * 1000);
    });
  }

  ngOnInit() {

  }

  gotoLogin() {
  	window.open(this.urlService.apiUrl + 'auth/login', '_self');
  }

  logout() {
    this.authService.logout();
  }


}

<header class="header-component">
        <div class="section left">
            <div class="image"></div>
            <h1 class="application-title">{{.projectName}}</h1>
        </div>
    <div class="section right">
        

<div class="logged-in-user-section">
    <div class="user-menu-button" *ngIf="username">
        <fa-icon [icon]="faUser"></fa-icon>
        <!--<span class="fas fa-user user-icon"></span>-->
        <span class="username">{{username}}</span>
        <fa-icon [icon]="faCaretDown"></fa-icon>
        {{ expiry | date: 'medium'}}
        <!-- <span class="fas fa-caret-down"></span> -->
    </div>
    <button mat-flat-button (click)="gotoLogin()" color="primary" *ngIf="!username">Login</button>
    <button mat-flat-button (click)="logout()" color="primary" *ngIf="username">Logout</button>
<!-- 
    <Button text={'Logout'} priority={ButtonPriority.Primary} onClick={this.props.logout} /> -->
</div>


    </div>
</header>
