// cmd/setup/templates/app/src/app/components/navigation-bar/navigation-bar.component.ts
import { Component, OnInit } from '@angular/core';
import { NamedRoute, routes } from '../../routes';

@Component({
  selector: 'app-navigation-bar',
  templateUrl: './navigation-bar.component.html',
  styleUrls: ['./navigation-bar.component.scss']
})
export class NavigationBarComponent implements OnInit {
  displayRoutes: Array<NamedRoute>;
  constructor() {
  		this.displayRoutes = routes.filter(r => r.displayName);
  }

  ngOnInit() {
  }

}

<nav class="navigation-bar-component">
	<a mat-button *ngFor="let r of displayRoutes" [routerLink]="r.path" routerLinkActive="active-link" class="router-link">
		{{ r.displayName }}
    </a>
</nav>

// cmd/setup/templates/app/src/components/NavigationBar/NavigationBar.component.tsx
import * as React from 'react';
import { hot } from 'react-hot-loader/root';
import { Link } from 'react-router-dom';
import routes, { Route } from '@app/routes';
import './NavigationBar.scss';

export class NavigationBarComponent extends React.Component {
  render = () => {
    return (
      <nav className="navigation-bar-component">
        {routes.map((route, key) => this.renderRoute(route, key))}
      </nav>
    );
  };

  renderRoute = (route: Route, key: number) => {
    if (route.displayName) {
      let classNames = 'route-button';
      if (route.path === location.pathname) {
        classNames += ' active-route';
      }
      return (
        <Link className={classNames} to={route.path} key={key}>
          <div className="route-button-inner">
            <span>{route.displayName}</span>
          </div>
        </Link>
      );
    }
  };
}

export default hot(NavigationBarComponent);
