// cmd/setup/templates/app/src/app/components/gov-website-banner/gov-website-banner.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-gov-website-banner',
  templateUrl: './gov-website-banner.component.html',
  styleUrls: ['./gov-website-banner.component.scss']
})
export class GovWebsiteBannerComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}

<div class="gov-website-banner-component">
	<div class="flag-image"></div>
	<span>An official website of the United States government</span>
</div>

// cmd/setup/templates/app/src/components/common/GovWebsiteBanner/GovWebsiteBanner.tsx
import * as React from 'react';
import { hot } from 'react-hot-loader/root';
import './gov-website-banner.scss';

export class GovWebsiteBannerComponent extends React.Component {
  render = () => {
    return (
      <div className="gov-website-banner-component">
        <div className="flag-image" />
        <span>An official website of the United States government</span>
      </div>
    );
  }
}

export default hot(GovWebsiteBannerComponent);
